Redo rspec
dasileker/enumerable_redo pull request #2
Opened 2020-10-12 09:21 UTC by dasileker

### Testing Ruby with RSpec - Enumerable methods
In this milestone, I used RSpec to create a testing file for our enumerable methods project.

2020-10-12 17:52 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Amine Zerradi** 
Nice job so far with your first submission :muscle:  :muscle: 
Your project meets most of the requirements. You have done a great effort testing different scenarios :clap: :clap: :clap:  
We still need to fix some details:

- [ ] For each method, test positive and negative scenarios, you might use "to_not_eql" or "to_not be_an".
- [ ] the description of each test should be unique. The description of the test must be more explicit.
- [x] Use 'require_relative' instead of 'require'.
- [ ] In your README file, explain how to run your tests.


Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-10-13 11:28 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey team :+1: 

You did a great job. Your tests are descriptive, and they cover a lot of different cases. However, we do have a few pending issues that we still need to address: 

- [x] Each method should be wrapped in one describe block

- [ ] You have some repetition in your _it_ descriptions

- [ ] I can see that you added negative scenarios for the _my_each_, but I believe that the previous TSE asked to add the negative scenarios for all the methods. 
![image](https://user-images.githubusercontent.com/61479648/95854816-dd27e200-0d2d-11eb-9c0f-2cd3d852be36.png)

- [ ] You also have the wrong Git flow (you should have a development branch, and push the changes to that branch)

Kindly check the inline comments below to see more.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-10-13 11:28 UTC, expjazz commented on spec/enum_redo_spec.rb
> +    describe 'it should return to Enumerator if there no block' do
- [ ] Each method should be wrapped in one describe block (sometimes you have more than one describe per method).

![image](https://user-images.githubusercontent.com/61479648/95854092-d8166300-0d2c-11eb-8619-44b6e56a2059.png)

2020-10-13 11:28 UTC, expjazz commented on spec/enum_redo_spec.rb
> +      it 'should not return to Enumerator if there no block' do
- [ ] I can see that you are testing different cases, but your _"it"_ description remains the same. Kindly update that.

2020-10-14 09:12 UTC, dasileker commented on spec/enum_redo_spec.rb
> +    describe 'it should return to Enumerator if there no block' do
thanks, man I was sick, I was struggling to finish.  I hope now is good

2020-10-14 09:14 UTC, dasileker commented on spec/enum_redo_spec.rb
> +      it 'should not return to Enumerator if there no block' do
sorry for that I was thinking that I should do it but it turns not necessary, and sorry for the workflow too. like I said I was sick

2020-10-14 09:44 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Well done :clap: :clap: :clap: @dasileker, thanks for making the required changes :hammer: 

now you can merge your project is approved.

## Happy Coding :tophat:

2020-10-14 09:47 UTC, merged